permalink: /:categories/:year/:month/:day/:title 


title : iyounggo

gems: [jekyll-paginate]
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一直在学习，却连最简单的玩儿都没有学会<br>离开世界之前，玩儿好，学好！"
sidebar-avatar: /img/avatar-iyounggo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
